[project]
name = "lib.dtos"
version = "0.0.0"
requires-python = "~=3.12"
dependencies = [
    "msgspec >= 0.18.6",
]

[tool.uv]
dev-dependencies = []

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
