[tool.poetry]
name = "acme-core"
version = "0.1.0"
description = ""
authors = ["Ben Fasoli <ben@pngme.com>"]
readme = "README.md"
packages = [{include = "acme_core"}]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
