services:
  api:
    image: api:latest
    build:
      context: ../
      dockerfile: docker/Dockerfile.api

  worker:
    image: worker:latest
    build:
      context: ../
      dockerfile: docker/Dockerfile.worker
