services:
  api:
    image: api:latest
    build:
      context: ..
      dockerfile: services/api/Dockerfile
    ports:
      - 8080:8080

  worker:
    image: worker:latest
    build:
      context: ..
      dockerfile: services/worker/Dockerfile

  postgres:
    image: postgres:15
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    tmpfs:
      - /var/lib/postgresql/data
    volumes:
      - ./sql:/docker-entrypoint-initdb.d:ro
