FROM python:3.12-slim-bookworm

ENV PORT 8080
ENV PYTHONUNBUFFERED 1
ENV TZ UTC

WORKDIR /app

COPY . .
RUN pip install services/api

CMD [ "uvicorn", "run",  "--host=0.0.0.0", "--port=${PORT}", "src.app:app"]
