[project]
name = "lib.dtos"
version = "0.0.0"
requires-python = "~=3.13.0"
dependencies = [
    "pydantic ~= 2.8",
]

[tool.uv]
dev-dependencies = []

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
