[project]
name = "core"
version = "0.0.0"
requires-python = "~=3.13.0"
dependencies = []

[dependency-groups]
dev = []

[build-system]
requires = ["uv_build>=0.7.3,<0.8.0"]
build-backend = "uv_build"
