name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: Lint & test
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install uv 🐍
        uses: astral-sh/setup-uv@v9.0.0
        with:
          version: "0.11.32"
          enable-cache: true

      - name: Install python dependencies 🐍
        run: uv sync --locked

      - name: Lint 🔬
        run: make lint

      - name: Test 🧑‍🔬
        run: make test

      - name: Build 🏗️
        run: make build
