name: Test

on: push

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Lint and test
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - run: echo noop
      # - format
      # - lint
      # - test